name: Functions OpenAI Extension Feature Request
description: File a Functions OpenAI Extension Feature report
title: "Request a feature"
labels: ["funcai", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        This form will help you to fill in a feature request for Azure Functions OpenAI Extension.
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have occurred?

  - type: dropdown
    id: language
    attributes:
      label: What language of preference?
      default: 0
      options:
        - Dotnet (OOP)
        - Java
        - NodeJS (Typescript / Javascript)
        - PowerShell
        - Python
        - Other - Explain below

  - type: textarea
    id: code-snippet
    attributes:
      label: Relevant sample code snipped
      description: Please copy and paste any relevant code snippet of how you want the feature to be used. (This will be automatically formatted into code, so no need for backticks)
      render: shell

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
