trigger: none # ensure this is not ran as a CI build

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /eng/ci/templates/build-variables.yml@self
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: Build
        displayName: 'Build And Test'
        dependsOn: []
        jobs:
          - template: /eng/ci/templates/run-integration-tests.yml@self
