trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.md'

# CI only, does not trigger on PRs.
pr: none

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /eng/ci/templates/build-variables.yml@self
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: BuildDotNet
        displayName: 'Build DotNet'
<<<<<<< HEAD
        dependsOn: []
        variables:
          Codeql.BuildIdentifier: openai_extension
          Codeql.Language: csharp,javascript,powershell,python
          Codeql.RunSourceLanguagesInSourceAnalysis: true
        jobs:
          - template: /eng/ci/templates/build-local.yml@self

      - stage: BuildJava
        displayName: 'Build Java'
        dependsOn: []
=======
        variables:
          Codeql.BuildIdentifier: csharp_openai_extension
          Codeql.Language: csharp
        jobs:
          - template: /eng/ci/templates/build-and-publish.yml@self
            parameters:
              poolName: $(OfficialPool)

      - stage: BuildJava
        displayName: 'Build Java'
>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
        variables:
          Codeql.BuildIdentifier: java_openai_extension
          Codeql.Language: java
        jobs:
          - template: /eng/ci/templates/build-java-library.yml@self
          - template: /eng/ci/templates/build-java-samples.yml@self

<<<<<<< HEAD
      - stage: BuildDotnetNuget
        displayName: 'Build DotNet Nuget'
        dependsOn: []
=======
      - stage: Build Dotnet Nuget
        displayName: 'Build DotNet Nuget'
>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
        jobs:
          - template: /eng/ci/templates/build-nuget.yml@self
