# This build is used for public PR and CI builds.

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.md'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.md'

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

variables:
  - template: /eng/ci/templates/build-variables.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: Build
        variables:
          Codeql.BuildIdentifier: csharp_openai_extension_public
          Codeql.Language: csharp
        jobs:
          - template: /eng/ci/templates/build-local.yml@self
