# This build is used for public PR and CI builds.

pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**.md'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - '**.md'

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Build
      jobs:
      - template: /eng/ci/templates/build-and-publish.yml@self
