pr:
  branches:
    include:
      - main
  paths:
    include:
      - java-library/*
      - samples/*/java/*
<<<<<<< HEAD
      - eng/ci/templates/build-java-library.yml
      - eng/ci/templates/build-java-samples.yml
=======
      - build/build-java.yml
>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
    exclude:
      - '**.md'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - java-library/*
      - samples/*/java/*
<<<<<<< HEAD
      - eng/ci/templates/build-java-library.yml
      - eng/ci/templates/build-java-samples.yml
=======
      - build/build-java.yml
>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
    exclude:
      - '**.md'

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

<<<<<<< HEAD
=======
variables:
  Codeql.BuildIdentifier: java_openai_extension_public
  Codeql.Language: java

>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
<<<<<<< HEAD

    sdl:
      codeql:
        compiled:
          enabled: true # still only runs for default branch
        language: java
        buildIdentifier: java_openai_extension_public

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

=======
>>>>>>> 745aef5 (Move to 1ES PT, Official and Public Builds (#81))
    stages:
      - stage: BuildJava
        displayName: 'Build Java'
        jobs:
          - template: /eng/ci/templates/build-java-library.yml@self
          - template: /eng/ci/templates/build-java-samples.yml@self
